### ISSUE TITLE
Local variable in ResourceDelegate generated code needs to avoid naming conflicts

### ISSUE THREAD

**Issue by ias-dt** [ArcBees/gwtp-extensions#16]
Create a service with a parameter named _action_ and in the _ResourceImpl_ there will be something like:
```
    @Override
    public foo.mypackage.LogInResult login(
            foo.mypackage.LogInRequest action) {
        RestAction<foo.mypackage.LogInResult> action = ((AuthenticationResourceImpl) resource).login$action(
                action);
        execute(action);

        return null;
    }
```
And this will result in an error like:
> Tracing compile failure path for type 'foo.mypackage.AuthenticationResourceDelegate'
>                Errors in 'C:\workspaces\foo.mypackage.MyModule\compile-2\gen\foo\mypackage\AuthenticationResourceDelegate.java'
>                   Line 37: The method login$action(LogInRequest) in the type AuthenticationResourceImpl is not applicable for the arguments (RestAction<LogInResult>)
>                   Line 37: Duplicate local variable action

**Comment by Chris-V** [comment]
Thanks for reporting. That should be a quick fix :)

**Comment by ias-dt** [comment]
Why is there a local variable generated? Is it really needed?

**Comment by Chris-V** [comment]
Mainly readability, but this one could be removed. I need to look at all the templates and fix all possible declarations though

**Comment by ias-dt** [comment]
Thanks for looking into this :)
