### ISSUE TITLE
dispatch-rest-delegates should keep same version number as gwtp-dispatch-rest

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/gwtp-extensions#23]
dispatch-rest-delegates last release is 1.5 and gwtp is on 1.5.1.

Can we keep the versioning in sync or fold delegates into gwtp-dispatch-rest?

**Comment by olafleur** [comment]
Yeah, it's a good idea too keep them in sync.

**Comment by olafleur** [comment]
As far as I know, they are keep in sync. Closing.
